name: Smoke Test Football Cli

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: src/FootballCli

    steps:
    - uses: actions/checkout@v3
    - name: Build Football Cli 
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: src/FootballCli/global.json
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Smoke Test
      env:
        # Additional checks are run at startup in Development mode
        FOOTBALL_CLI_VALIDATE_EXAMPLES: true
      run: dotnet run --no-build -- competitions 
